[tool.pytest.ini_options]
addopts = "-ra -q --maxfail=1 --strict-markers --strict-config --cov=backend/src --cov-report=term-missing --cov-report=xml:backend/coverage.xml"
testpaths = [
  "backend/tests"
]
pythonpath = [
  "backend/src"
]
markers = [
  "unit: unit tests",
  "integration: integration tests"
]
filterwarnings = [
  "ignore::DeprecationWarning",
]
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
log_date_format = "%H:%M:%S"
